# Generated by Django 6.0.1 on 2026-02-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('total_students', models.PositiveIntegerField()),
                ('subtitle', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CountryOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('key_highlights', models.TextField(help_text='Comma separated or bullet points')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='country.country')),
            ],
        ),
        migrations.CreateModel(
            name='LivingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='living_expense_icons/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='living_expenses', to='country.country')),
            ],
        ),
        migrations.CreateModel(
            name='PopularCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('avg_annual_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_courses', to='country.country')),
            ],
        ),
        migrations.CreateModel(
            name='StudyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_level', models.CharField(max_length=100)),
                ('avg_annual_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_costs', to='country.country')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('world_rank', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('avg_tuition_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='country.country')),
            ],
        ),
        migrations.CreateModel(
            name='VisaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('icon', models.ImageField(upload_to='visa_icons/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_requirements', to='country.country')),
            ],
        ),
    ]
