# Generated by Django 6.0.1 on 2026-02-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_livingexpense_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryoverview',
            name='image',
            field=models.ImageField(blank=True, upload_to='country_overviews/ '),
        ),
    ]
