# Generated by Django 6.0.1 on 2026-02-11 16:05

import filehub.fields
import tinymce.models
from django.db import migrations, models
from django.utils.text import slugify


def populate_country_slugs(apps, schema_editor):
    Country = apps.get_model("country", "Country")
    existing = set(
        Country.objects.exclude(slug__isnull=True).values_list("slug", flat=True)
    )

    for country in Country.objects.all():
        if country.slug:
            continue

        base = slugify(country.country_name) or "country"
        base = base[:240]
        slug = base
        counter = 1

        while slug in existing:
            counter += 1
            suffix = f"-{counter}"
            slug = f"{base[:255 - len(suffix)]}{suffix}"

        country.slug = slug
        country.save(update_fields=["slug"])
        existing.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_countryoverview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_country_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='image',
            field=filehub.fields.ImagePickerField(blank=True, file_ext=None, file_type=None, upload_to='country_overviews/ '),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='key_highlights',
            field=tinymce.models.HTMLField(help_text='Comma separated or bullet points'),
        ),
    ]
