# Generated by Django 6.0.1 on 2026-02-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_country_slug_alter_countryoverview_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livingexpense',
            name='icon',
            field=models.CharField(blank=True, help_text='Huge Icon class name', max_length=100),
        ),
        migrations.AlterField(
            model_name='visarequirement',
            name='icon',
            field=models.CharField(blank=True, help_text='Huge Icon class name', max_length=100),
        ),
    ]
