# Generated by Django 6.0.1 on 2026-02-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_alter_livingexpense_icon_alter_visarequirement_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='countryoverview',
            options={'verbose_name': 'Country Overview', 'verbose_name_plural': 'Country Overviews'},
        ),
        migrations.AlterModelOptions(
            name='livingexpense',
            options={'verbose_name': 'Living Expense', 'verbose_name_plural': 'Living Expenses'},
        ),
        migrations.AlterModelOptions(
            name='popularcourse',
            options={'verbose_name': 'Popular Course', 'verbose_name_plural': 'Popular Courses'},
        ),
        migrations.AlterModelOptions(
            name='studycost',
            options={'verbose_name': 'Study Cost', 'verbose_name_plural': 'Study Costs'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterModelOptions(
            name='visarequirement',
            options={'verbose_name': 'Visa Requirement', 'verbose_name_plural': 'Visa Requirements'},
        ),
        migrations.AlterField(
            model_name='livingexpense',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='popularcourse',
            name='avg_annual_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studycost',
            name='avg_annual_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
