# Generated by Django 6.0.1 on 2026-02-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_alter_country_options_alter_countryoverview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='avg_tuition_cost',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
