# Generated by Django 6.0.1 on 2026-02-17 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_alter_university_avg_tuition_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('city_description', models.CharField(max_length=200)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('currency_description', models.CharField(blank=True, max_length=200)),
                ('intake_months', models.CharField(blank=True, max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_highlights', to='country.country')),
            ],
            options={
                'verbose_name': 'Key Highlight',
                'verbose_name_plural': 'Key Highlights',
            },
        ),
    ]
