# Generated by Django 6.0.1 on 2026-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_keyhighlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
