"""
Django settings for counsultancybackend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY environment variable must be set. "
        "Generate a secure key using: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )

DEBUG = os.getenv("DEBUG", "False").lower() == "true"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Environment check
if not DEBUG and "localhost" in ALLOWED_HOSTS:
    raise ValueError(
        "DEBUG is False but 'localhost' is in ALLOWED_HOSTS. "
        "Configure proper domain names in ALLOWED_HOSTS environment variable."
    )

load_dotenv(BASE_DIR / "env")
# Application definition

INSTALLED_APPS = [
    'dashub',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'nested_admin',
    'corsheaders',
    'django_filters',
    "tinymce",
    "filehub",
    
    # Your apps
    'blog',
    'event', 
    'contact',
    'country',
    'testperperation',
    'home',
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Configuration
# In production, always restrict to specific origins
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in development

CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000"
).split(",") if not DEBUG else ["http://localhost:3000", "http://127.0.0.1:3000"]

ROOT_URLCONF = 'counsultancybackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'counsultancybackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    # 🔥 Allow public access by default
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "AUTH_HEADER_TYPES": ("Bearer",),
} 


X_FRAME_OPTIONS = "SAMEORIGIN"

# Security Headers for Production
if not DEBUG:
    # HTTPS/SSL
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookie security
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Strict'
    SESSION_COOKIE_SAMESITE = 'Strict'
    
    # Additional security
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_SECURITY_POLICY = {
        'default-src': ("'self'",),
        'script-src': ("'self'", "'unsafe-inline'"),
        'style-src': ("'self'", "'unsafe-inline'"),
        'img-src': ("'self'", "data:", "https:"),
    }
else:
    # Development settings (less strict)
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "localhost,127.0.0.1").split(",")

DASHUB_SETTINGS = {
    "site_logo": "/static/logo.svg",
    "site_icon": "/static/favicon.ico",
    "theme_color": "#255078",
    "border_radius": "5px",
    "hide_models": [
        "auth", 
        "auth.group", 
        "home",
        "home.contactinfo",
        "home.socialmedia",
        "home.studyabroadcard",
        "home.successstorycard",
        "home.about",
        "home.core_value",
        "home.teammember",
        "testperperation",
        "testperperation.testcard",
        "testperperation.testformat",
        "testperperation.testpreparation",
        "testperperation.whychoose",
        "country",
        "country.country",
        "country.popularcourse",
        "country.studycost",
        "country.university",
        "country.livingexpense",
        "country.visarequirement",
        "country.keyhighlight",
        "blog",
        "blog.blog",
        "blog.blogtype",
        "event",
        "event.event",
        "event.eventtype",
        "contact",
        "contact.contact",  
        "contact.counselingsession",      
    ],
    "default_orders": {
        "auth": 10,
        "auth.group": 4,
        "home": 20,
        "testperperation": 30,
        "country": 40,
        "blog": 50,
        "event": 60,
        "contact": 70,

        
    },
    "custom_links": {
        "auth": [
            {
                "model": "auth.post" 
            },
            {
                "name": "User Management",
                "icon": "fa-solid fa-users",
                "submenu": [
                    {"model": "auth.user", "order": 1},
                    {"model": "auth.group", "order": 2},
                   
                ]
            },
        ],
        "Menu": [
            {
                "name": "Home",
                "icon": "fa-solid fa-house",
                "url": "/admin/home",
                "submenu": [    
                    {"name": "Contact Info", "url": "/admin/home/contactinfo", "order": 1},
                    {"name": "Contact Media","url": "/admin/home/socialmedia/", "order": 2},
                    {"name": "Study Abroad ", "url": "/admin/home/studyabroadcard/", "order": 3},
                    {"name": "Success Story ", "url": "/admin/home/successstorycard/", "order": 4},
                    {"name": "About ", "url": "/admin/home/about/", "order": 5},
                    {"name": "Core Value ", "url": "/admin/home/core_value/", "order": 6},
                    {"name": "Team Member ", "url": "/admin/home/teammember/", "order": 7},
                ],
            }
        ,
            {
                "name": "Test Preparation",
                "icon": "fa-solid fa-book",
                "url": "/admin/testperperation",
                "submenu": [
                    {"model": "testperperation.testpreparation", "order": 1},
                    
                ],
            }
        ,
            {
                "name": "Country Info",
                "icon": "fa-solid fa-globe",
                "url": "/admin/country",
                "submenu": [
                        {"model": "country.country","url": "/admin/country/country/", "order": 1},
                        {"model": "country.popularcourse","url": "/admin/country/popularcourse/", "order": 2},
                        {"model": "country.studycost","url": "/admin/country/studycost/", "order": 3},
                        {"model": "country.university","url": "/admin/country/university/", "order": 4},
                        {"model": "country.livingexpense","url": "/admin/country/livingexpense/", "order": 5},
                        {"model": "country.visarequirement","url": "/admin/country/visarequirement/", "order": 6},
                        {"model": "country.keyhighlight","url": "/admin/country/keyhighlight/", "order": 7},
                      
                       ],
                }
            ,
                {
                    "name": "Blog",
                    "icon": "fa-solid fa-newspaper",
                    "url": "/admin/blog",
                    "submenu": [
                        {"model": "blog.blog", "order": 1},
                        {"model": "blog.blogtype", "order": 2},
                    ],
                },
            
                {
                    "name": "Event",
                    "icon": "fa-solid fa-calendar-days",
                    "url": "/admin/event",
                    "submenu": [
                        {"model": "event.event", "order": 1},
                    ],
                }
            ,
                {
                    "name": "Contact",
                    "icon": "fa-solid fa-envelope",
                    "url": "/admin/contact/contact",
                    "submenu": [
                        {"model": "contact.contact", "order": 1},
                        {"model": "contact.counselingsession", "order": 2},
                    ],
                }
            ],


    },
    "submenus_models": ["auth.group"],
   
    "icons": {
        "auth": "fa-regular fa-user",
        "auth.user": "fa-regular fa-user",
    },
    "custom_js": [
        "/static/js/admin.js",
    ],
    "custom_css": [
        "/static/css/admin.css",
    ]
}




# filehub setup
# Login URL for file access control
FILEHUB_LOGIN_URL = "/login/"


TINYMCE_DEFAULT_CONFIG = {
    "height": 300,
    "width": "100%",
    "menubar": True,
    "plugins": "advlist autolink lists link image charmap preview code fullscreen media table",
    "toolbar": "undo redo | formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link image media | code fullscreen preview",
    "images_upload_url": "/tinymce/upload/",
}
