"""
Django settings for counsultancybackend project.

Generated by 'django-admin startproject' using Django 6.0.
"""

import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

"""
CORE SETTINGS
Basic configuration including security keys, debug mode, and host authorization.
"""
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY environment variable must be set. "
        "Generate a secure key using: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )

DEBUG = os.getenv("DEBUG", "False").lower() == "true"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "launchpadglobal.com.np,www.launchpadglobal.com.np").split(",")

ROOT_URLCONF = 'counsultancybackend.urls'
WSGI_APPLICATION = 'counsultancybackend.wsgi.application'

if not DEBUG and "localhost" in ALLOWED_HOSTS:
    raise ValueError(
        "DEBUG is False but 'localhost' is in ALLOWED_HOSTS. "
        "Configure proper domain names in ALLOWED_HOSTS environment variable."
    )

"""
APP DEFINITION
Registration of Django core, third-party libraries, and internal project applications.
"""
INSTALLED_APPS = [
    # Django core
    'dashub',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'nested_admin',
    'corsheaders',
    'django_filters',
    "tinymce",
    "filehub",
    "solo",
    
    # Local apps
    'blog',
    'event', 
    'contact',
    'country',
    'testperperation',
    'home',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

"""
DATABASE & CACHE
Connectivity settings for PostgreSQL and Redis-based caching.
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", 5432),
    }
}

if not DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://redis:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {'max_connections': 50},
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
            },
            'KEY_PREFIX': 'consultancy',
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-local',
        }
    }

"""
TEMPLATES
Configuration for HTML rendering engines and context processors.
"""
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

"""
AUTH & PASSWORDS
User authentication rules and password complexity validation.
"""
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

"""
I18N
Internationalization and localization settings for language and time zone.
"""
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kathmandu'
USE_I18N = True
USE_TZ = True

"""
STATIC & MEDIA
Handling of static assets (JS/CSS) and user-uploaded media files.
"""
STATIC_URL = os.getenv("STATIC_URL", "/static/")
STATIC_ROOT = os.path.join(BASE_DIR, "public", "static")
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

"""
CORS & CSRF
Cross-Origin Resource Sharing and Cross-Site Request Forgery protection settings.
"""
def _normalize_origin_list(origins):
    normalized = []
    for origin in origins:
        origin = origin.strip()
        if not origin: continue
        if "://" not in origin: origin = f"http://{origin}"
        normalized.append(origin)
    return normalized

CORS_ALLOW_ALL_ORIGINS = DEBUG
default_cors = "https://launchpadglobal.com.np,https://www.launchpadglobal.com.np"
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", default_cors).split(",") if not DEBUG else ["http://localhost:3000", "http://127.0.0.1:3000"]
CORS_ALLOWED_ORIGINS = _normalize_origin_list(CORS_ALLOWED_ORIGINS)

default_csrf = "https://launchpadglobal.com.np,https://www.launchpadglobal.com.np"
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", default_csrf).split(",") if not DEBUG else ["http://localhost:3000", "http://127.0.0.1:3000"]
CSRF_TRUSTED_ORIGINS = _normalize_origin_list(CSRF_TRUSTED_ORIGINS)

"""
REST FRAMEWORK settings
Django Rest Framework configuration including authentication, permissions, and throttling.
"""
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

if not DEBUG:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ]
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": "300/hour",
        "user": "2000/hour",
        "anon_burst": "30/min",
        "user_burst": "100/min",
        "contact": "10/hour",
        "counseling": "5/hour",
    }

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

"""
THIRD-PARTY APP SETTINGS
Configuration for integrated third-party services like Dashub, Filehub, and TinyMCE.
"""

# Dashub
DASHUB_SETTINGS = {
    "site_logo": "/static/logo.svg",
    "site_icon": "/static/favicon.ico",
    "theme_color": "#255078",
    "border_radius": "5px",
    "hide_models": [
        "auth", "auth.group", "home", "home.contactinfo", "home.socialmedia",
        "home.studyabroadcard", "home.successstorycard", "home.about", "home.core_value",
        "home.teammember", "testperperation", "testperperation.testcard",
        "testperperation.testformat", "testperperation.testpreparation",
        "testperperation.whychoose", "country", "country.country", "country.popularcourse",
        "country.studycost", "country.university", "country.livingexpense",
        "country.visarequirement", "country.keyhighlight", "blog", "blog.blog",
        "blog.blogtype", "event", "event.event", "event.eventtype", "contact",
        "contact.contact", "contact.counselingsession",
    ],
    "default_orders": {
        "auth": 10, "auth.group": 4, "home": 20, "testperperation": 30,
        "country": 40, "blog": 50, "event": 60, "contact": 70,
    },
    "custom_links": {
        "auth": [
            {"model": "auth.post"},
            {
                "name": "User Management",
                "icon": "fa-solid fa-users",
                "submenu": [{"model": "auth.user", "order": 1}, {"model": "auth.group", "order": 2}]
            },
        ],
        "Menu": [
            {
                "name": "Home", "url": "/admin/home", "icon": "hgi hgi-stroke hgi-home-11",
                "submenu": [
                    {"name": "Contact Info", "model": "home.contactinfo", "order": 1},
                    {"name": "Contact Media", "model": "home.socialmedia", "order": 2},
                    {"name": "Study Abroad", "model": "home.studyabroadcard", "order": 3},
                    {"name": "Success Story", "model": "home.successstorycard", "order": 4},
                    {"name": "About", "model": "home.about", "order": 5},
                    {"name": "Core Value", "model": "home.core_value", "order": 6},
                    {"name": "Team Member", "model": "home.teammember", "order": 7},
                ],
            },
            {
                "name": "Test Preparation", "model": "testperperation.testpreparation"
            },
            {
                "name": "Countries", "model": "country.country"
            },
            {
                "name": "Blog", "model": "blog.blog"
            },
            {
                "name": "Event", "model": "event.event",
            },
            {
                "name": "Contact", "url": "/admin/contact/contact", "icon": "hgi hgi-stroke hgi-message-01",
                "submenu": [
                    {"name": "Contact", "model": "contact.contact", "order": 1, "icon": "hugeicons-comment-01"},
                    {"name": "Counseling session", "model": "contact.counselingsession", "order": 2, "icon": "hugeicons-user-card-id"}
                ],
            }
        ],
    },
    "submenus_models": ["auth.group"],
    "icons": {
        "auth.user": "hgi hgi-stroke hgi-user-03",
        "testperperation.testpreparation": "hgi hgi-stroke hgi-mortarboard-02",
        "country.country": "hgi hgi-stroke hgi-globe-02",
        "blog.blog": "hgi hgi-stroke hgi-news",
        "event": "hugeicons-calendar-03",
        "event.event": "hgi hgi-stroke hgi-calendar-02"
    },
    "custom_js": ["/static/js/admin.js"],
    "custom_css": ["/static/css/admin.css"]
}

# Filehub
FILEHUB_LOGIN_URL = "/login/"

# TinyMCE
TINYMCE_DEFAULT_CONFIG = {
    "height": 300,
    "width": "100%",
    "menubar": True,
    "plugins": "advlist autolink lists link image charmap preview code fullscreen media table",
    "toolbar": "undo redo | formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link image media | code fullscreen preview",
    "images_upload_url": "/tinymce/upload/",
}

"""
SECURITY Headers
Security-related headers and middleware configuration for production environments.
"""
X_FRAME_OPTIONS = "SAMEORIGIN"

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Strict'
    SESSION_COOKIE_SAMESITE = 'Strict'
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_SECURITY_POLICY = {
        'default-src': ("'self'",),
        'script-src': ("'self'", "'unsafe-inline'"),
        'style-src': ("'self'", "'unsafe-inline'"),
        'img-src': ("'self'", "data:", "https:"),
    }
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

"""
LOGGING Configuration
Logging setup for monitoring application behavior and debugging errors.
"""
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
        },
        "simple": {
            "format": "%(levelname)s %(message)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
        },
    },
}
