# Generated by Django 6.0.1 on 2026-02-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_counselingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingsession',
            name='preferred_time',
            field=models.CharField(max_length=20),
        ),
    ]
