# Generated by Django 6.0.1 on 2026-02-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_counselingsession_preferred_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingsession',
            name='counseling_mode',
            field=models.CharField(max_length=100),
        ),
    ]
