# Generated by Django 6.0.1 on 2026-02-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_counselingsession_counseling_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselingsession',
            options={'verbose_name': 'Counseling Session', 'verbose_name_plural': 'Counseling Sessions'},
        ),
    ]
