# Generated by Django 6.0.1 on 2026-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_counselingsession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='counselingsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Counseling Session', 'verbose_name_plural': 'Counseling Sessions'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='full_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='preferred_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-created_at'], name='contact_con_created_263a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['status', '-created_at'], name='contact_con_status_59d242_idx'),
        ),
        migrations.AddIndex(
            model_name='counselingsession',
            index=models.Index(fields=['-created_at'], name='contact_cou_created_eab6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='counselingsession',
            index=models.Index(fields=['status', '-created_at'], name='contact_cou_status_3c010c_idx'),
        ),
        migrations.AddIndex(
            model_name='counselingsession',
            index=models.Index(fields=['preferred_date'], name='contact_cou_preferr_7f57b1_idx'),
        ),
    ]
