# Generated by Django 6.0.1 on 2026-02-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=255, unique=True),
        ),
    ]
