# Generated by Django 6.0.1 on 2026-02-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_blog_type_remove_blog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
