# Generated by Django 6.0.1 on 2026-02-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='descriptions',
        ),
    ]
