# Generated by Django 6.0.1 on 2026-02-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='category',
        ),
    ]
