# Generated by Django 6.0.1 on 2026-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_name_blog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published_date', 'title'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-published_date'], name='blog_blog_publish_733b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['category', '-published_date'], name='blog_blog_categor_4a1581_idx'),
        ),
    ]
