# Generated by Django 6.0.1 on 2026-02-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
