# Generated by Django 6.0.1 on 2026-02-04 08:17

import filehub.fields
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_date_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=filehub.fields.ImagePickerField(file_ext=None, file_type=None, upload_to='events/'),
        ),
    ]
