# Generated by Django 6.0.1 on 2026-02-04 08:38

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_description_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_item', tinymce.models.HTMLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnings', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universities', tinymce.models.HTMLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='event.event')),
            ],
        ),
    ]
