# Generated by Django 6.0.1 on 2026-02-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventagenda_eventlearning_eventuniversity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
