# Generated by Django 6.0.1 on 2026-02-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyabroadcard',
            options={'verbose_name': 'Study Abroad', 'verbose_name_plural': 'Study Abroad'},
        ),
        migrations.AlterModelOptions(
            name='successstorycard',
            options={'verbose_name': 'Success Story', 'verbose_name_plural': 'Success Stories'},
        ),
    ]
