# Generated by Django 6.0.1 on 2026-02-12 05:16

import filehub.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_studyabroadcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstorycard',
            name='image',
            field=filehub.fields.ImagePickerField(blank=True, file_ext=None, file_type=None, null=True, upload_to='success_story_cards/'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='social_media',
            field=models.CharField(blank=True, help_text='huge icons', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studyabroadcard',
            name='icons',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studyabroadcard',
            name='image',
            field=filehub.fields.ImagePickerField(file_ext=None, file_type=None, upload_to='study_abroad_cards/'),
        ),
    ]
