# Generated by Django 6.0.1 on 2026-02-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_successstorycard_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyabroadcard',
            name='button_text',
            field=models.CharField(default='Learn More', max_length=100),
        ),
        migrations.AddField(
            model_name='studyabroadcard',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyabroadcard',
            name='icons',
            field=models.TextField(blank=True, help_text='use huge icons', null=True),
        ),
    ]
