# Generated by Django 6.0.1 on 2026-02-12 07:29

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_studyabroadcard_button_text_studyabroadcard_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='social_media',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='business_hour',
            field=tinymce.models.HTMLField(blank=True, help_text='huge icons', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='email',
            field=tinymce.models.HTMLField(blank=True, help_text='email eg: test@gmail.com', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=tinymce.models.HTMLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studyabroadcard',
            name='button_text',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studyabroadcard',
            name='icons',
            field=models.CharField(default=2, help_text='use huge icons', max_length=500),
            preserve_default=False,
        ),
    ]
