# Generated by Django 6.0.1 on 2026-02-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_contactinfo_social_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='business_hour',
            field=models.TextField(blank=True, help_text='huge icons', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='email eg: test@gmail.com', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.TextField(max_length=50),
        ),
    ]
