# Generated by Django 6.0.1 on 2026-02-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contactinfo_business_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='business_hour',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
