# Generated by Django 6.0.1 on 2026-02-16 08:39

import filehub.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_teammember_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=filehub.fields.ImagePickerField(blank=True, file_ext=None, file_type=None, null=True, upload_to='team_members/'),
        ),
    ]
