# Generated by Django 6.0.1 on 2026-02-16 10:44

import filehub.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_core_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('image', filehub.fields.ImagePickerField(blank=True, file_ext=None, file_type=None, null=True, upload_to='about_images/')),
            ],
        ),
    ]
