# Generated by Django 6.0.1 on 2026-02-10 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='testperperation.testpreparation')),
            ],
        ),
        migrations.CreateModel(
            name='TestFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('question_type', models.CharField(max_length=200)),
                ('topics_covered', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_formats', to='testperperation.testpreparation')),
            ],
        ),
        migrations.CreateModel(
            name='TestCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='testperperation.testpreparation')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completion_time', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Enroll Now', max_length=100)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='testperperation.testpreparation')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('focus_area', models.CharField(max_length=200)),
                ('activities', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='testperperation.testpreparation')),
            ],
            options={
                'ordering': ['week'],
            },
        ),
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='testprep/icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose', to='testperperation.testpreparation')),
            ],
        ),
    ]
