# Generated by Django 6.0.1 on 2026-02-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testperperation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecurriculum',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='focus_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursepricing',
            name='button_text',
            field=models.CharField(blank=True, default='Enroll Now', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursepricing',
            name='completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursepricing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursepricing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='testcard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcard',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testformat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testformat',
            name='question_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testformat',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testformat',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testformat',
            name='topics_covered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testoverview',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testoverview',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testpreparation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testpreparation',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='whychoose',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whychoose',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='testprep/icons/'),
        ),
        migrations.AlterField(
            model_name='whychoose',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
