# Generated by Django 6.0.1 on 2026-02-12 16:12

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testperperation', '0002_alter_coursecurriculum_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecurriculum',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whychoose',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
